kind: pipeline
name: pipeline-example-maven

steps:
- name: Maven编译
  image: maven:3-jdk-7
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn clean install

- name: 构建镜像  
  image: plugins/docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    username: 
      from_secret: docker_user
    password: 
      from_secret: docker_pass
    repo: registry.cn-shanghai.aliyuncs.com/hxf168482/hxf168482
    tags: latest


#- name: Kubernetes 部署
#  image: guoxudongdocker/kubectl:v1.14.1
#  volumes:
#  - name: kube
#    path: /root/.kube
#  commands:
#    - sed -i "s/#Tag/${DRONE_BUILD_NUMBER}/g" deployment.yaml
#    - kubectl apply -f deployment.yaml




#
#trigger:
#  branch:
#  - master